### ISSUE TITLE
label.size parameter missing

### ISSUE THREAD

**Issue by dfernandezperez** [enblacar/SCpubr#14]
Hi Enrique!

I have started to play with your package and I'm enjoying it a lot, thanks!

I was trying some dimplots, and it seems that the parameter "label.size" from SCpubr::do_DimPlot() is missing. In your book manual (Basic plots > 1 Dim plots > 1.4 label the clusters) there's an example where you are modifying the size of the labels with the parameter label.size. I am using SCpubr 1.0.4 (the same as indicated in the book), but that parameter is missing in my version (I can't neither find it in the source code of the function linked in the manual book). Am I doing something wrong?

Thanks a lot!

**Comment by enblacar** [comment]
Hi @dfernandezperez,

Thanks for using my package! I am happy to read that it's useful to you!

The only error here is that I forgot to add to the webpage that these parameters will be implemented in SCpubr `v1.1.0`. Sorry about that!

It is normal that you can not find it in the CRAN version or any of the [github releases](https://github.com/enblacar/SCpubr/releases). The only way you can access these new features now is by installing SCpubr from GitHub using the last commit. 

Check out the [`NEWS`](https://github.com/enblacar/SCpubr/blob/main/NEWS.md#scpubrdo_dimplot) file! Anything under `v1.0.4.9000` will appear  in the next CRAN update, including   `label.size` and `label.box` for `SCpubr::do_DimPlot()`! 

The update will be implemented probably after Christmas, as I am in holidays right now :P

Merry Christmas and happy plotting!
Enrique

**Comment by enblacar** [comment]
Hi @dfernandezperez,

SCpubr version [1.1.0](https://github.com/enblacar/SCpubr/releases/tag/v1.1.0) is already on CRAN!

Please consider updating to get all the new functionalities:

```r
install.packages("SCpubr")
```

Thanks again for using the package!
Enrique
