### ISSUE TITLE
The "do_alluvialplot" function is not working

### ISSUE THREAD

**Issue by hmlopezbertoni** [enblacar/SCpubr#15]
I updated to the latest dev. version (1.0.4) available but this function seems to be in version 1.0.4.9000 - where can I download this version?

**Comment by enblacar** [comment]
Hi @hmlopezbertoni,

Thanks for using my package!

This is a function that will become available once I update SCpubr to v1.1.0 (please, refer to the [**documentation guide**](https://enblacar.github.io/SCpubr-book/13-AlluvialPlot.html)). Some minor tweaks are still needed and this function is still on development phase.

If you still want to use it, you need to download SCpubr from GitHub using the **last commit**. The bundles in the release tab will not do it. 

Hope this helps.

Best,
Enrique

**Comment by hmlopezbertoni** [comment]
Hi Enrique, thanks for the response.

Your package is awesome, it makes scRNA-seq analysis accessible to folks with limited coding capabilities (like myself). Keep up the great work!

**Comment by enblacar** [comment]
Hi @hmlopezbertoni,

SCpubr version [1.1.0](https://github.com/enblacar/SCpubr/releases/tag/v1.1.0) is already on CRAN!

Please consider updating to get all the new functionalities:

```r
install.packages("SCpubr")
```

Thanks again for using the package!
Enrique
