### ISSUE TITLE
Feature plot that also has cluster annotation as colored dots/boxes with legend rather than labels on clusters

### ISSUE THREAD

**Issue by JesseRop** [enblacar/SCpubr#20]
Dear developers, 

Thank you very much for the great tool which significantly improves single-cell plots.
I'm wondering if there's a way to label feature plots clusters using colours without putting text labels on the clusters. This can be helpful when making several feature plots for different genes and using one legend to orient the users on the positions of clusters. Below is an example to illustrate the idea that I have put together in powerpoint.

![image](https://user-images.githubusercontent.com/18431376/215298852-ee198492-2590-4e34-a5c4-bc2e772e6784.png)

Here is an example from a paper by Wu et al 2021 which shows a Dimplot. It would be nice to be able to implement it in featureplot

![image](https://user-images.githubusercontent.com/18431376/215298959-66cab7f0-3b54-4b89-af8d-a4a4695a760f.png)

**Comment by enblacar** [comment]
Hi @JesseRop,

Thanks for using my package and for taking the time to generate the examples!

I think I do not entirely comprehend the overall usefulness of the example besides a dedicated DimPlot side by side. In your upper example, clusters that lie in between a blob of cells will not be able to be colored "on the outside" of the blob like you do. Hence, the only thing that came to mind was using some kind of averaged UMAP_1/UMAP_2 position per each cluster:

![image](https://user-images.githubusercontent.com/42321264/215984874-c9dd5d88-2125-425e-ba62-9160abd12a87.png)

This is how my approach looks like. On the top row, a regular DimPlot and FeaturePlot. On the bottom row: left - FeaturePlot with a dot centered around each of the clusters. right - same as left but also with the borders around the cell blobs also colored by their respective clusters (works well for self-contained clusters, but will fail for clusters in between blobs of cells). This can be managed with a new parameter called `group.by`. 

You can also control the alpha of the new borders, by default set to 0.1:
![image](https://user-images.githubusercontent.com/42321264/215986347-6e096998-37d5-4cb5-9ef4-b22845e17619.png)


Let me know if this is what you wanted! It will roll out on the next CRAN update.
Best,
Enrique

**Comment by JesseRop** [comment]
HI Enrique,

Many thanks for your prompt action on this!
Your idea is so much better than what I was suggesting. 
I'm happy with any of the options;(1) centered dot, (2) borders or (3)both. 
When will you be rolling out the next update? Can I just use the developers version on github?

**Comment by enblacar** [comment]
Hi @JesseRop,

I do not know when this will happen as I am rather busy on my PhD project and CRAN updates require a lot of pre-planning to make sure nothing breaks once it is out. I am just polishing some details before committing this to CRAN. I can let you know once I do it and you can download SCpubr from the last commit to get this new feature.

As always, be mindful that anything can be broken when using the latest commit version! It's sometimes difficult to catch all the side effects when introducing big changes to a function like ones required for this new feature.

I will mark this as closed! Feel free to re-open if if you have further feedback!

Best,
Enrique

**Comment by enblacar** [comment]
Hi @JesseRop,

Apologies for the delay! I have just committed the code to GitHub. I have been working in major changes to many functions, so if you want to install the last commit be aware that most of the Heatmap-related functions will likely break, as I am switching to ggplot2 for such plots.

Best,
Enrique

**Comment by JesseRop** [comment]
No worries @enblacar, I understand how busy s PhD can get. 
Thank you very much for the update!!
