### ISSUE TITLE
Replacing LIANA's plots with SCpubr

### ISSUE THREAD

**Issue by dbdimitrov** [enblacar/SCpubr#21]
Hi @enblacar,

I was thinking, perhaps I should completely replace LIANA's plots with the Ligand-Receptor ones from SCpubr in the next few updates.

In the end, they are very much with liana's, with yours being of higher quality.

Perhaps, one thing that I'm missing currently in LIANA is a ligand-receptor dotplot across samples. 
Would you be open to having one in SCpubr? I can do a PR with the basis for the function (likely not as in-depth and as cutomizable as your standard). I can also keep that one to LIANA alone.

Let me know what your thoughts are on this! 

Best,
Daniel

**Comment by dbdimitrov** [comment]
PS. I'm asking in relation to having a dotplot in this tutorial (i.e. across contexts/samples):
https://saezlab.github.io/liana/articles/liana_cc2tensor.html

**Comment by enblacar** [comment]
Closing this issue as we discussed it in person!

Enrique
