### ISSUE TITLE
do_DimPlot: sizes.highlight not working when raster = TRUE

### ISSUE THREAD

**Issue by dfernandezperez** [enblacar/SCpubr#22]
Hey there!

I was doing some plots trying to highlight specific cells when I found that, if raster = TRUE when using do_DimPlot, the sizes.highlight argument is ignored. I can change the point size of all cells using pt.size, but I can't using sizes.highlight. Here a small code to reproduce the problem:

```
library(Seurat)
library(tidyverse)
data("pbmc_small")

cells_to_highlight <- sample(Cells(pbmc_small), 10)

# Raster + highlight
SCpubr::do_DimPlot(
  sample = pbmc_small, 
  cells.highlight = cells_to_highlight,
  sizes.highlight = 16,
  pt.size = 8,
  raster = TRUE
) & coord_fixed()

# NO raster + highlight
SCpubr::do_DimPlot(
  sample = pbmc_small, 
  cells.highlight = cells_to_highlight,
  sizes.highlight = 4,
  pt.size = 1,
  raster = FALSE
) & coord_fixed()
```

Thanks a lot!!

Daniel

**Comment by enblacar** [comment]
Hi @dfernandezperez,

Thanks for using my package! And nice catch on that bug!

Luckily, it was a simple bug to solve. I just made the changes and it looks fine now to me:

```r
p1 <- SCpubr::do_DimPlot(sample,
                         idents.highlight = "1",
                         plot.title = "Raster = F | sizes.highlight = 1")

p2 <- SCpubr::do_DimPlot(sample,
                         idents.highlight = "1",
                         sizes.highlight = 3,
                         plot.title = "Raster = F | sizes.highlight = 3")

p3 <- SCpubr::do_DimPlot(sample,
                         idents.highlight = "1",
                         raster = TRUE,
                         plot.title = "Raster = T | sizes.highlight = 1")

p4 <- SCpubr::do_DimPlot(sample,
                         idents.highlight = "1",
                         sizes.highlight = 3,
                         raster = TRUE,
                         plot.title = "Raster = T | sizes.highlight = 3")
p <- (p1 | p2) / (p3 | p4)
p
```

![dimplot](https://user-images.githubusercontent.com/42321264/219424507-f7a8ba9f-0e77-4764-a706-4f94343580a4.png)

As always, one needs to play with `pt.size` and `sizes.highlight` to get the rasterised figure to look like the non-rasterised one.

I just pushed the changes to GitHub and will roll out on the next CRAN update! 
Best,
Enrique
