### ISSUE TITLE
How to present cell communication results in groups

### ISSUE THREAD

**Issue by tu12dou** [enblacar/SCpubr#23]
I have two groups and I want to compare the differences in cell communication between them, but I haven't found any relevant code.
Could you provide the related code.
Thank you

**Comment by enblacar** [comment]
Hi,

Can you please elaborate more on your problem? Do you want to compare a whole set of source-target interactions across a third variable? If so, this is not implemented currently in the package.

Best,
Enrique

**Comment by tu12dou** [comment]
I have single-cell RNA sequencing data from two groups, group A and group B. Group A is the control group and group B is the drug treatment group. I would like to display and compare the cell communication results from both groups on a single graph. Can you please provide guidance or code for how to do this

**Comment by enblacar** [comment]
Hi, 

Comparisons across datasets are not currently implemented in SCpubr. It is still pending to do. All you can do now is to use the results from an output of liana, where you have A and B combined an used the condition as source/target. But this might not be strictly what you want to visualize.

This is currently outside the scope of `SCpubr::do_LigandReceptorPlot()`. Please resort to official liana documentation to generate the plot you need, it might be already implemented in `liana`.

Best,
Enrique
