### ISSUE TITLE
'do_SankeyPlot' is not an exported object from 'namespace:SCpubr'

### ISSUE THREAD

**Issue by tqh003** [enblacar/SCpubr#24]
Hi enblacar,
Thank you for developing such an excellent package. I encountered an error when I tried the do_SankeyPlot, in which 'cm' is my preprocessed Seurat object.
library(SCpubr)
library(Seurat)
library(dplyr)
p1<-SCpubr::do_SankeyPlot(sample = cm,
                          first_group = "RNA_snn_res.0.1",
                          last_group = "seurat_clusters",
                          type = "sankey")
Error: 'do_SankeyPlot' is not an exported object from 'namespace:SCpubr'.
Do you know what problem cause this error?

**Comment by tqh003** [comment]
Hi enblacar,
Sorry for missing your note.
I have tried the do_AlluvialPlot, it works very well. 
Thanks again.

**Comment by enblacar** [comment]
Hi @tqh003,

Thank you for using it!

Glad that you found out about the note! You can still access it via the github version, though. Check the packages [releases](https://github.com/enblacar/SCpubr/releases/tag/v1.1.2-dev-stable)! 

Best,
Enrique
