### ISSUE TITLE
Error using do_GroupwiseDEPlot

### ISSUE THREAD

**Issue by ccruizm** [enblacar/SCpubr#26]
Hello @enblacar!

I am having a great time using your package. Unfortunately, I am facing an issue using `do_GroupwiseDEPlot`. The error is:
```
Error in grid.Call.graphics(C_downvppath, name$path, name$name, strict): Viewport '-log10(Adjusted P-value)_heatmap_body_1_1' was not found
Traceback:

1. SCpubr::do_GroupwiseDEPlot(sample = dmg, de_genes = de_genes, 
 .     min.cutoff = 1)
2. ComplexHeatmap::draw(ht_list, heatmap_legend_list = list_legends, 
 .     heatmap_legend_side = if (legend.position %in% c("top", "bottom")) {
 .         "bottom"
 .     } else {
 .         "right"
 .     }, padding = ggplot2::unit(c(5, 5, 5, 5), "mm"), ht_gap = ggplot2::unit(heatmap_gap, 
 .         "cm"))
3. ComplexHeatmap::draw(ht_list, heatmap_legend_list = list_legends, 
 .     heatmap_legend_side = if (legend.position %in% c("top", "bottom")) {
 .         "bottom"
 .     } else {
 .         "right"
 .     }, padding = ggplot2::unit(c(5, 5, 5, 5), "mm"), ht_gap = ggplot2::unit(heatmap_gap, 
 .         "cm"))
4. .local(object, ...)
5. grid.draw(p)
6. grid.draw.gTree(p)
7. recordGraphics(drawGTree(x), list(x = x), getNamespace("grid"))
8. drawGTree(x)
9. grid.draw(x$children[[i]], recording = FALSE)
10. grid.draw.grob(x$children[[i]], recording = FALSE)
11. recordGraphics(drawGrob(x), list(x = x), getNamespace("grid"))
12. drawGrob(x)
13. preDraw(x)
14. preDraw.grob(x)
15. pushvpgp(x)
16. pushgrobvp(x$vp)
17. pushgrobvp.vpPath(x$vp)
18. downViewport(vp, strict = TRUE, recording = FALSE)
19. downViewport.vpPath(vp, strict = TRUE, recording = FALSE)
20. grid.Call.graphics(C_downvppath, name$path, name$name, strict)
```

Any thoughts on what could it be?

Thanks in advance!

**Comment by enblacar** [comment]
Hi @ccruizm,

Thanks for using my package! I am happy that you find it useful to your research!

Unfortunately, these kind of cryptic errors are one of the mejor reasons why I am currently implementing a shift of all heatmap-based functions to `ggplot2` for version `2.0.0` of `SCpubr`.  I honestly do not know what could be going wrong. If you are OK sending me your DE object, I can try to have a look!

Alternatively,  the counterpart version of `SCpubr::do_GroupwiseDEPlot()` in the future version `2.0.0` should be ready to use. It has undergone a couple of tweaks (the most noticeable is that for the p-values I am not using the highest possible integer number when I get infinite values after log-transforming, I am just using the highest non-infinite value). However, you should get the desired output by running the same line of code as in your  example!

If you decide to try it out, please go for the latest commit possible, and revert back to the official version afterwards, as the current development commits are far from being a stable version.

Hope this helps!
Enrique

This is an example output with my toy data using a similar input:
```r
SCpubr::do_GroupwiseDEPlot(sample = sample, 
                           de_genes = de_genes, 
                           min.cutoff = 1, 
                           na.value = "grey90", 
                           group.by = c("seurat_clusters", "orig.ident"))
```

![plot](https://user-images.githubusercontent.com/42321264/228558989-903635f5-93dd-4e4f-8bae-334e8e08194b.png)

**Comment by enblacar** [comment]
Hi @ccruizm! 

Closing this for the time being. Hope the hotfix helped! Feel free to reopen this issue if not!

Enrique
