### ISSUE TITLE
Changing colors 

### ISSUE THREAD

**Issue by eldant** [enblacar/SCpubr#27]
Hello @enblacar ,

Thank you for such a great package!
I am just having an issue with changing the colors in a Dimplot for the three identities of my object.
The analogous Seurat command works fine.
I am sure I am missing something obvious...

SCpubr::do_DimPlot(sample = FiltID, colors.use = c("#00A9FF","#F8766D","#0CB702"))
Error: The names of provided colors does not match the number of unique values in the selected grouping variable (levels(object), group.by or split.by).

**Comment by eldant** [comment]
Solved! just got it from another closed issue. Sorry for not checking earlier.
Thanks!

**Comment by enblacar** [comment]
Hello @eldant!

Thanks for using my package!

Indeed, many of `SCpubr`'s functions required a `named list` with the desired colors to work. Perhaps this is something I should report more clearly once this error triggers. I will do that for next update!

Feel free to contact me if you have any other issues!
Enrique
