### ISSUE TITLE
Error: 'save_Plot' is not an exported object from 'namespace:SCpubr'

### ISSUE THREAD

**Issue by athulmenon** [enblacar/SCpubr#28]
Hi,

Thank you for this amazing package!

I am receiving this strange error when using 'SCpubr::[save_Plot](https://rdrr.io/pkg/SCpubr/man/save_Plot.html)'

Error: 'save_Plot' is not an exported object from 'namespace:SCpubr'

I installed the cran version first, but later installed the dev version and reloaded the library.

Plotting works, but saving the plot have the above issue. Do you have any suggestions.

Regards,
Athul

**Comment by enblacar** [comment]
Hi @athulmenon,

Thanks for using my package!

Are you following the guidelines written [here](https://github.com/enblacar/SCpubr/releases/tag/v1.1.2-dev-stable)?

If you do the following:

```r
# Unload SCpubr.
detach("package:SCpubr")

# Remove old SCpubr
remove.packages("SCpubr")

# CLOSE THE R SESSION AND START A NEW ONE

# Install development verision
devtools::install_github("enblacar/SCpubr", ref = "v1.1.2-dev-stable")

# Load SCpubr.
library("SCpubr")
```

I am quite sure you will successfully install SCpubr `v1.2.0.900` (dev) that includes the function that way.

Let me know if it works!
Enrique

**Comment by athulmenon** [comment]
Perfect!

I was following the steps but not restarting the R. Thanks a lot.

Regards,
Athul
