### ISSUE TITLE
Share SCpubr book for version 1.1.2

### ISSUE THREAD

**Issue by ccruizm** [enblacar/SCpubr#29]
Hello @enblacar!

I just saw you are planning a major update of your excellent package! That's great. However, I would like to know whether it is still possible to share the previous reference manual you had at [enblacar.github.io/SCpubr-book/](https://enblacar.github.io/SCpubr-book/). It would be helpful to have access to it until the next version is fully released. 

Many thanks for considering my request!

**Comment by ccruizm** [comment]
Sorry, I did not read the new site carefully, and you have the link for the previous documentation. My bad. Looking forward top seeing the next release!

**Comment by enblacar** [comment]
Hi @ccruizm,

Glad you found out the new link! Perhaps I should rewrite the on-going website to make it more clear how to access the old one.

Hopefully the update will not take long to be released!

Best,
Enrique
