### ISSUE TITLE
Error using do_DimPlot when using split.by

### ISSUE THREAD

**Issue by ccruizm** [enblacar/SCpubr#30]
Hello @enblacar,

I have an issue using `do_DimPlot` when using the argument split.by. When I use group.by it generates the plot, but once I change it to split.by using the same column in the metadata, I get the error below:
```
Error in `[.data.frame`(data, , group): undefined columns selected
Traceback:

1. SCpubr::do_DimPlot(obj, raster = TRUE, reduction = "umap", 
 .     split.by = "type", ncol = 3, legend.position = "none", 
 .     font.size = 16)
2. Seurat::DimPlot(sample.use, reduction = reduction, group.by = if (is.null(group.by)) {
 .     split.by
 . } else {
 .     group.by
 . }, label = label, dims = dims, repel = repel, label.box = label.box, 
 .     label.color = label.color, label.size = label.size, na.value = na.value, 
 .     shuffle = shuffle, order = order, pt.size = pt.size, cols = colors.use, 
 .     raster = raster, raster.dpi = c(raster.dpi, raster.dpi))
3. is.factor(x = data[, group])
4. data[, group]
5. `[.data.frame`(data, , group)
6. stop("undefined columns selected")
```
What do you think the problem is?

**Comment by enblacar** [comment]
Hi @ccruizm,

Thanks for pointing out the bug!

This is weird. I get the expected output from the same lines of code, both in `v1.1.2` and in the development version. 

Perhaps we can work together to narrow the bug down:

- Which version of `SCpubr` and `Seurat` are you using?
- Can you describe a bit more your `type` metadata column?
    - Is it a `character` or a `factor`?
    - Does it contain  `NA`s? 
    - If it is a factor, do you have empty levels? This meaning, that the factor level is there but 0 cells are assigned to it.
- And perhaps more importantly, does this happen `consistently across other metadata columns` or is it something specific of your `type` column?

Best,
Enrique

**Comment by enblacar** [comment]
Hi @ccruizm,

I am closing this for now as I am unable to replicate the error with the current information I have.

Please feel free to reopen this if you have further info! I am more than willing to get to the bottom of this bug!

Best,
Enrique
