### ISSUE TITLE
BUG | FUNCTION NAME | BRIEF DESCRIPTION

### ISSUE THREAD

**Issue by LeoBLMitz** [enblacar/SCpubr#33]
**Bug:**
```
# Your description of the bug goes here.
```

**Reproducible example:**
```r
# Your reproducible example goes here.
# How to make a good one: https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/
```

**Error log:**
```r
# Paste the full error log here
```

**SCpubr version:**
```r
# Put the version of SCpubr that you are using here.
# Can be checked by: utils::packageVersion("SCpubr")
```

**Session info:**
```r
# Include the output of sessionInfo() here.
```

**Comment by enblacar** [comment]
Hi @LeoBLMitz,

Thanks for reaching out! Unfortunately, your issue template seems to be empty. Closing this for now. Feel free to open a new issue if you have any questions!

Enrique

**Comment by LeoBLMitz** [comment]
When and witch the bug append say it passes through the threshold deal means beating by him self as often it remained correlated and accurated through the pass_way_meaning that it would be able to get the game in the same way as it is played

**Comment by LeoBLMitz** [comment]
- @

**Comment by LeoBLMitz** [comment]
- [ ] - ूरोकूोुीूोबैतौतबौैकबचरनटसबहत्ेोमिि@[_________[[](https://support.google.com/families/answer/7103340?hl=en)](https://support.google.com/families/answer/7103340?hl=en)_________](https://support.google.com/families/answer/7103340?hl=en)![image](https://github.com/enblacar/SCpubr/assets/118720672/48f8c97b-2330-4163-b885-1dd679a0ff3d)ंे्बूाूोेौैेुुुिेु्ीि
