### ISSUE TITLE
BUG | `.GetAssayData` | Incorrect assumptions about SeuratObject versions

### ISSUE THREAD

**Issue by mojaveazure** [enblacar/SCpubr#38]
Code for `.GetAssayData()` assumes that SeuratObject v4.1.3 is the last version of SeuratObject for the v4 cycle https://github.com/enblacar/SCpubr/blob/main/R/utils.R#L3283-L3290
This assumption is incorrect; we are trying to submit v4.1.4 to handle the upcoming removal of rgeos from CRAN, and this assumption in SCpubr will cause failures in our upcoming submission

For reference, `SeuratObject::GetAssayData()` will continue to work in SeuratObject v5 and will work for both v3 and v5 assays. Once v5 is released, we will eventually start throwing warnings about the usage of `GetAssayData()` and move users and downstream packages to `LayerData()`, but that will not happen until SeuratObject v5.1 at the earliest (and may be later). But as SeuratObject v5 is not on CRAN, v5 assumptions should not be made in packages that are also on CRAN

**Comment by enblacar** [comment]
Hi @mojaveazure,

Sorry for the late reply! Many, many thanks for taking the time to point this problem out!

I will update the code ASAP to fix this and submit a hotfix to CRAN. 

Best,
Enrique
