### ISSUE TITLE
BUG | do_EnrichmentHeatmap | features.order not working?

### ISSUE THREAD

**Issue by jcshuy** [enblacar/SCpubr#41]
Hi there, I'm rather new to single cell analyses so I'm sorry if this question is due to my inexperience. I am trying to run a Heatmap using UCell scores from a Seurat object. My input_gene_list looks something like this

```

genes <- as.dataframe(read_csv("genes.csv")) #dataframe with different rows of marker genes
genesets <- list(Macrophages = as.vector(genes$macros), 
                 Microglia = as.vector(genes$microglia), 
                 Phagocytes = as.vector(genes$phagocytes))
seurat.object <- AddModuleScore_UCell(seurat.object, genesets, BPPARAM = BPPARAM, name = NULL)
```
where genesets is a named list and each list contains character gene symbols, and seurat.object is a seurat object. 
I manually changed the names of the list items in genesets as I am unsure if I am allowed to share the specific information (the actual object has around 10 items)

My code for the heatmap is
```
do_EnrichmentHeatmap(seurat.object, genesets, flavor = "UCell", group.by = "group", features.order = c(names(genesets)))
```
Which generates a proper heatmap without features.order with the gene set groups out of order (e.g., "Microglia", "Phagocytes", "Macrophages"). 

When adding features.order it doesn't throw an error but does generates an incorrect plot:
<img width="256" alt="Screenshot 2023-09-28 at 2 43 53 PM" src="https://github.com/enblacar/SCpubr/assets/115590807/1d6fab94-a82b-4bc4-add4-2ef22ca7679b">

I'm not sure if there's something I'm doing wrong? The class of names(genesets) is character. I have tried manually ordering them as a vector in the function as well but it gets the same result. Does anyone know if there is a different way to implemen this or if this is due to a bug? Thank you for your time and help!

**Comment by enblacar** [comment]
Hi @jcshuy,

Thanks for using my package! And really, apologies for the late reply. 

I think I have found the issue. Does your plot when you do not set `features.order` have the output with the suffix `_scaled` in your list of genes? If so, try running it with `scale_scores = FALSE` and it should work.

I have noted down the bug and I will fix it in the next update. 

Let me know if that works! Feel free to reopen the issue if it does not.

Update `2.0.2` is out on CRAN, fixing some critical problems with dependencies. I highly suggest you to update to this latest version of `SCpubr`.

Best,
Enrique
