### ISSUE TITLE
Output of Featureplot and Dimplot are of different size

### ISSUE THREAD

**Issue by TdzBAS** [enblacar/SCpubr#52]
Hi @enblacar ,

thanks for nice tool. Is there a way to ensure the same height and width for the output of the feature and dimplots?
![image](https://github.com/enblacar/SCpubr/assets/91309592/e0f5b016-d89e-4051-b7c0-719755c5d965)

Best,
Tolga

**Comment by enblacar** [comment]
Hi @TdzBAS,

Thanks for using my package!

Unfortunately, this seems to fall back to the original behaviour of `Seurat::DimPlot()` and `Seurat::FeaturePlot()`.  See the example below, using `SCpubr` and `Seurat`:

![example](https://github.com/enblacar/SCpubr/assets/42321264/063e1796-b890-4024-b721-6b7a2b7114d5)

Fixing this is currently out of the scope of what I can do right now, sorry. Please feel free to open a new Issue if there is anything else I can help with!

Best,
Enrique
