### ISSUE TITLE
Do_FeaturePlot | Set custom scales/limits OR copy Seurat::FeaturePlot keep.scale parameter

### ISSUE THREAD

**Issue by npotemkin** [enblacar/SCpubr#55]
It would be great if there were a way to set custom limits to the scales on feature plots, eg via calling ```scale_fill_gradientn()``` from ```ggplot2```.
Alternatively, a way to copy the ```keep.scale``` parameter from Seurat::FeaturePlot, allowing for standardisation of scales across multiple plots.
Thanks!

**Comment by enblacar** [comment]
Hi @npotemkin,

Thanks for using my package!

If I understand your request correctly, there are two main scenarios:

- A: Limits are not set across features (default) or not.
- B: Limits are set across subsets when using `split.by`. 

In B, this is enforced, so you will always have a plot where each UMAP shares the same axes limits. 

In A,  I implemented the use of `min.cutoff` and `max.cutoff` to tweak each individual UMAP separately (also works in B). If you want to restrict the maximum value of the scales across, let's say, four features, use `max.cutoff = rep(2, 4)`. Right now there is no way to enforce it across features, as `SCpubr` will throw an error if the value provided to `max.cutoff` exceeds the maximum value of the feature. However, if this is not the case, you can provide the maximum value to `max.cutoff` and that should do the trick!

I will have a look into implementing a similar behaviour as in `Seurat` for the next update. 

Hope that helps!
Enrique

**Comment by npotemkin** [comment]
Hi Enrique,
Thanks for your quick response! I probably could have explained myself better.
This request came off the back of my other bug report - trying to plot multiple features from a list as a grid. 
eg:
```r
gene.highlight <- c("Kcnj8", "Klrb1c", "S1pr5", "Ifit")
idents = c("0", "1", "6")
do_FeaturePlot(seu_obj, features = gene_highlight, idents.highlight = idents)
```

I'm therefore not using ```split.by```, but rather just wanting to standardise the legend scale across multiple plots (especially when plotting using patchwork).

Having the option to specify eg. ```limits = c(0,4)``` would be amazing!
Thanks again.
