### ISSUE TITLE
How to create custom mappings from p-values to annotation for BoxPlot

### ISSUE THREAD

**Issue by NicoHadas** [enblacar/SCpubr#65]
Hello, 

Thank you for the great package.

As described in the vignette for boxplots it is possible to create custom mappings for p-values. I was wondering how this would be possible with my custom mapping: `c("****"=0.0001,"***"=0.001, "**"=0.01, "*"=0.05)`. 

I try to add it to the map_signif_level argument but parameter map_signif_level needs to be of class logical.

Please advise.

**Comment by enblacar** [comment]
Hi @NicoHadas,

Thank you for using my package! Please accept my apologies for the delay in answering this. During the last three months, I have been deeply immersed in my PhD thesis writing. Therefore, I could not invest much time in `SCpubr`'s maintenance.

Indeed, this is a bug, thanks for reporting it!. It seems that, in this function, I am always expecting `map_signif_levels` to always be a `logical`. Therefore, with the current version, you cannot provide custom mappings. I have corrected this mistake and it will roll out on the next version of `SCpubr`! 

Let me know if there is anything else I can help you with!

Best,
Enrique
