### ISSUE TITLE
Show Genenames in featureplot for feature vector

### ISSUE THREAD

**Issue by TdzBAS** [enblacar/SCpubr#66]
Hi @mojaveazure,

thanks for your awesome tool!

I cant see how I can show the featurenames, if I plot a featurevector:
![image](https://github.com/enblacar/SCpubr/assets/91309592/20282e27-d08b-45b9-9e11-e2d7bfca0c0e)

Do you have an idea?

Best,
Tolga

**Comment by enblacar** [comment]
Hi @TdzBAS,

Thanks for using my package!

Would it be possible if you could include the code that you used to generate this plot?
That will allow me to have a better understanding of the issue.

Many thanks!
Enrique

**Comment by TdzBAS** [comment]
Hi @enblacar,

thanks for your quick reply!

this is the code:
![image](https://github.com/enblacar/SCpubr/assets/91309592/8c5bc25d-cec8-40e7-ba52-ae6f539bb820)

So i want to see the featurenames above the featureplots.

Many Thanks!
Tolga

**Comment by enblacar** [comment]
Hi @TdzBAS,

I see! Can you please retry with `legend.position = "bottom"` and let me know if that works? 

Best,
Enrique

**Comment by TdzBAS** [comment]
thanks this worked! 

The title is now leftadjusted, can i center it?

![image](https://github.com/enblacar/SCpubr/assets/91309592/3b6f56c9-ad17-467f-810b-309ebd18c3fd)

**Comment by enblacar** [comment]
You can do it with:

```r
p <- p + ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
```

Glad it helped!
Enrique
