### ISSUE TITLE
Error while trying out the TF Activity inference analysis section from the tutorial 

### ISSUE THREAD

**Issue by aditisk** [enblacar/SCpubr#7]
Hi again @enblacar,

I am getting an error while trying to get prior network information while following the TF activity inference vignette. The error is pasted below:

`> network <- decoupleR::get_dorothea(organism = "human",levels = c("A", "B", "C"))
Error: 'import_dorothea_interactions' is not an exported object from 'namespace:OmnipathR'`

I am using `SCpubr_1.0.1` and I manually downloaded all the required dependencies. Any thoughts on how to fix this ?

Thanks.

**Comment by enblacar** [comment]
Hi @aditisk,

Both `SCpubr:: do_PathwayActivityPlot()` and `SCpubr:: do_TFActivityPlot()` expect you to have run `decoupleR` beforehand.

For this, you will need to install it: 

```r
install.packages("BiocManager")
BiocManager::install("decoupleR")
```

If it still does not work, try installing `OmnipathR` as well. Also, please consider updating to `SCpubr v1.0.2`, as it has new features and bug fixes.

Closing this for now, if the error still persists let me know!
Enrique
