### ISSUE TITLE
REQUEST | doDimPlot | Plot NA values of grouping values in background

### ISSUE THREAD

**Issue by jaakoobb** [enblacar/SCpubr#73]
Hi Enrique,

I have a question regarding the DimPlot() function, and I'm not sure if what I'm asking is already supported. When I use the group.by argument and there are NA values for that variable, is it possible to bring the plotting layer of those cells to the back (similar to the highlight.cells argument, in which all the unselected cells are grayed out and brought to the back).

My current code produces the following plot:

```r
do_DimPlot(gd, pt.size = 3, group.by="TRDV")+
  scale_color_manual(values=rev(pal_TR[1:6]), na.value="gray80")
```
![image](https://github.com/user-attachments/assets/19c98687-8441-4bbb-9750-0b10b63d953b)

**Feature request:**
```
# Essentially, in the above plot, I want all the grayed out NA values to be plotted behind all
# colored in cells (ideally, while those colored in cells are still shuffled)
```

**Example:**
```r
# Similar to what happens when cells.highlight is used (the problem here is, 
# that all selected cells are grouped together)
```
![image](https://github.com/user-attachments/assets/b99bb6b5-e377-4f6b-bb2e-47a5f8cfd41d)

**SCpubr version:**
```r
utils::packageVersion("SCpubr")
[1] ‘2.0.2’
```

**Comment by enblacar** [comment]
Hi @jaakoobb,

Thank you for using my package! There is no straight away parameter that handles this, as I do not generally expect `NA` in the metadata variables to plot, as they are also handled by `na.value` parameter in `SCpubr::do_DimPlot()`. 

However, I found a workaround for this. In short:
- You turn your metadata variable from a factor to a character (if it is a factor).
- Select all the `NA` values and turn it into a character value - i.e: `"Remove"`.
- Set the metadata variable as the `Idents` of the Seurat object via the `Seurat::Idents()` function.
- Plot the `DimPlot` using the `idents.keep` parameter and providing all the values but the one you wish to bring to the back.

And that should do it. Here is a code example of it:

```r
sample$seurat_clusters <- as.character(sample$seurat_clusters)
sample$seurat_clusters[is.na(sample$seurat_clusters)] <- "Remove"
sample$seurat_clusters <- as.factor(sample$seurat_clusters)
Seurat::Idents(sample)  <- sample$seurat_clusters

# Plot.
p <- SCpubr::do_DimPlot(sample, 
                        idents.keep = levels(sample)[levels(sample) != "Remove"])
p
```

This is how it looks with this hotfix:
![do_DimPlot_NA_Hotfix](https://github.com/user-attachments/assets/e56fe731-feae-4fcd-b4c3-6e7aed352704)

I will consider coding a workaround for this behaviour for the next update. Hope this helps in the meantime!

Enrique
