### ISSUE TITLE
Violin Feature Plots

### ISSUE THREAD

**Issue by TdzBAS** [enblacar/SCpubr#74]
Hi @enblacar,

thanks for your nice tool!
I like the dotplot visualization of features in different clusters. Is this also doable with violinplots?
like here:
![image](https://github.com/user-attachments/assets/a92d92c7-3b35-4324-8850-b070e7dfe92e)

Best,
Tolga

**Comment by enblacar** [comment]
Hi @TdzBAS,

Thank you for using `SCpubr`!

I believe those are called stacked violin plots. So far, this is not doable with the current implementation of `SCpubr::do_ViolinPlot()`, but I will be pretty much open to implement it in the near future! 

I will keep you updated through this Issue when changes are committed to the repo! 

Best,
Enrique

**Comment by TdzBAS** [comment]
Hi @enblacar,

that would be truly wonderful!

Best,
Tolga
