### ISSUE TITLE
label.font only works for legend but not for labels shown on umap

### ISSUE THREAD

**Issue by TdzBAS** [enblacar/SCpubr#76]
HI @enblacar,

thanks again for this wonderful tool!
I would like to request a new feature.
If I pass the argument label= T and label.font = "mono" for instance, it only affects the font style of the legend but not the labels shown on the umap plot.
It would be great if you could change this!

Best,
Tolga

**Comment by enblacar** [comment]
Hi @TdzBAS,

Thanks again for using my package!

I have fixed the bug, and will roll out on the next update. Also fixed it in `do_FeaturePlot()`. 

In the meantime, you can access it through the following github commit:

```r
devtools::install_github("enblacar/SCpubr", ref = "709734da4c41f0b1e39f2588a89bd62368fd70fc)
```

Best,
Enrique

**Comment by TdzBAS** [comment]
Hi @enblacar,

thanks for the fast response!

Unfortunately I receive this error, after installing the recommend branch:
![image](https://github.com/user-attachments/assets/970b11f9-c33e-4734-8a9f-7856f619f1b7)

Any ideas?
Best,
Tolga

**Comment by enblacar** [comment]
Use this commit instead!

```r
devtools::install_github("enblacar/SCpubr", ref = "3d7a80812ceb54ea1b5bb6d74cb316583d3f5346")
```

**Comment by enblacar** [comment]
Hi @TolgaDuz,

Thanks again for using `SCpubr`!

Just wanted to get back to you as `SCpubr` v3.0.0 is on CRAN now, including the fixes that resulted from this Issue!

Enrique
